version: '2.4'

services:
  flask: &flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: spun-flask
    expose:
      - 56733      
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - flask      

  nginx:
    image: nginx:alpine
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: spun-flask-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443      
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - flask
      
networks:
  default:
    name: default_network
  flask:
    driver: bridge
