"""Add otu related tables

Revision ID: 7f38e8d7a014
Revises: 6bc9666cd137
Create Date: 2024-11-19 13:32:12.484811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f38e8d7a014'
down_revision: Union[str, None] = '6bc9666cd137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otu_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otu_id')
    )
    op.create_table('otu_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otu_id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_type_id'], ['sequencing_analysis_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['otu_id'], ['otu.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['sequencing_samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otu_data')
    op.drop_table('otu')
    # ### end Alembic commands ###
