name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0  # Update to the latest version that supports Node.js 16

      - name: Update Google Cloud SDK
        run: gcloud components update

      - name: Authenticate with Google Cloud
        run: |
          echo ${{ secrets.GCP_SA_KEY }} > keyfile.json
          gcloud auth activate-service-account --key-file=keyfile.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Test access of runner user after os Login
        run: |
          gcloud compute ssh ${{ secrets.GCP_VM_INSTANCE }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="ls -l"