name: Deploy to Server

on:
  push:
    branches:
      - test-server

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add host key to known_hosts
        run: |
          ssh-keyscan -t rsa ${{ secrets.SERVER_DEPLOYMENT_IP }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Copy code to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_DEPLOYMENT_IP }}
          username: ${{ secrets.SERVER_DEPLOYMENT_USERNAME }}
          key: ${{ secrets.SERVER_DEPLOYMENT_PRIVATE_KEY }}
          script: |
            sudo rm -rf ${{ secrets.SERVER_DEPLOYMENT_APP_DIRECTORY }}
            mkdir -p ${{ secrets.SERVER_DEPLOYMENT_APP_DIRECTORY }}
            cat ~/.ssh/known_hosts
