name: Deploy Application

on:
  push:
    branches:
      - test-server

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deploy_to_non_google_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Copy code to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_DEPLOYMENT_IP }}
          username: ${{ secrets.SERVER_DEPLOYMENT_USERNAME }}
          key: ${{ secrets.SERVER_DEPLOYMENT_PRIVATE_KEY }}
          script: |
            sudo rm -rf ${{ secrets.SERVER_DEPLOYMENT_APP_DIRECTORY }}
            mkdir -p ${{ secrets.SERVER_DEPLOYMENT_APP_DIRECTORY }}
            scp -vvv -r ./* ${{ secrets.SERVER_DEPLOYMENT_USERNAME }}@${{ secrets.SERVER_DEPLOYMENT_IP }}:${{ secrets.SERVER_DEPLOYMENT_APP_DIRECTORY }}

