name: Deploy to Server

on:
  push:
    branches:
      - test-server

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  deploy_to_server:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Copy server code into APP DIRECTORY
        run: |
            pwd
            ls -al
            sudo cp -r ${{ github.event.repository.name }} ${{ secrets.SERVER_DEPLOYMENT_APP_DIRECTORY }}
            echo ${{ github.event.repository.name }}
