name: Deploy to Server

on:
  push:
    branches:
      - test-server

jobs:
  deploy_to_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Set up SSH and copy code to server
        run: |
          # Create SSH directory and known_hosts file
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.SERVER_DEPLOYMENT_IP }} >> ~/.ssh/known_hosts
          
          # Create private key file
          echo "${{ secrets.SERVER_DEPLOYMENT_PRIVATE_KEY }}" > ~/private_key_file
          chmod 600 ~/private_key_file
          
          # Securely copy repository code to the server
          scp -i ~/private_key_file -o UserKnownHostsFile=~/.ssh/known_hosts -r ./* ${{ secrets.SERVER_DEPLOYMENT_USERNAME }}@${{ secrets.SERVER_DEPLOYMENT_IP }}:${{ secrets.SERVER_DEPLOYMENT_APP_DIRECTORY }}

          # Run the make migrate command
          ssh -i ~/private_key_file -o UserKnownHostsFile=~/.ssh/known_hosts ${{ secrets.SERVER_DEPLOYMENT_USERNAME }}@${{ secrets.SERVER_DEPLOYMENT_IP }} "cd ${{ secrets.SERVER_DEPLOYMENT_APP_DIRECTORY }} && make migrate"
