name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Update to the latest version that supports Node.js 16

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.6.0
        with:
          service_account: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        # Configure gcloud with your project ID

      - name: Deploy code to Google Cloud VM
        run: |
          gcloud compute ssh ${{ secrets.GCP_VM_INSTANCE }} --zone=${{ secrets.GCP_ZONE }} --command="cd /var/lib/${{ secrets.GCP_PROJECT_DIRECTORY }} && git pull origin master"
