name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0  # Update to the latest version that supports Node.js 16

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0.7.0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        # Configure gcloud with your project ID

      - name: Deploy code to Google Cloud VM
        run: |
          gcloud compute ssh spun-test-8-nginx-docker-compose --zone=us-central1-a --command="git config --list --show-origin && who && cd /var/lib/spun-web-form && git pull origin master"
