name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - master
env:
  REPO_NAME: ${{ github.event.repository.name }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2.0.1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.0.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Test access of runner user after OS Login
        run: |
          gcloud compute ssh ${{ secrets.GCP_VM_INSTANCE }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="ls -l"

      - name: Check who the current user is
        run: |
          gcloud compute ssh ${{ secrets.GCP_VM_INSTANCE }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="who"

      - name: Copy code to VM
        run: |
          gcloud compute scp --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --recurse ${GITHUB_WORKSPACE} ${{ secrets.GCP_VM_INSTANCE }}:~/${{ github.event.repository.name }}

      - name: Chown the code to the correct user and copy it to correct folder
        run: |
          gcloud compute ssh ${{ secrets.GCP_VM_INSTANCE }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="sudo chown -R runner:runner "~/${{ github.event.repository.name }}/*" ; sudo cp -a "~/${{ github.event.repository.name }}/." ${{ secrets.GCP_PROJECT_DIRECTORY }}"

      - name: Test access of runner user after OS Login
        run: |
          gcloud compute ssh ${{ secrets.GCP_VM_INSTANCE }} \
            --zone=${{ secrets.GCP_ZONE }} \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --command="ls -l /home/runner/spun-web-form2"
